//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUDEditor.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HUDEditor.Assets.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing {0}..
        /// </summary>
        public static string error_hud_install {
            get {
                return ResourceManager.GetString("error_hud_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uninstalling {0}..
        /// </summary>
        public static string error_hud_uninstall {
            get {
                return ResourceManager.GetString("error_hud_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while toggling transparent viewmodels..
        /// </summary>
        public static string error_transparent_vm {
            get {
                return ResourceManager.GetString("error_transparent_vm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recognize file extension &apos;{0}&apos;..
        /// </summary>
        public static string error_unknown_extension {
            get {
                return ResourceManager.GetString("error_unknown_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string header_error {
            get {
                return ResourceManager.GetString("header_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string header_info {
            get {
                return ResourceManager.GetString("header_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string header_warning {
            get {
                return ResourceManager.GetString("header_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add a folder to the list of shared HUDs? This will add the folder locally but will not upload the HUD to TF2HUD.Editor&apos;s online database..
        /// </summary>
        public static string info_add_hud {
            get {
                return ResourceManager.GetString("info_add_hud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new HUD Editor update available. Would you like to download the latest release?.
        /// </summary>
        public static string info_app_update {
            get {
                return ResourceManager.GetString("info_app_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application to apply language change..
        /// </summary>
        public static string info_ask_restart {
            get {
                return ResourceManager.GetString("info_ask_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting a new background will override the current one. Use the &quot;Reinstall&quot; option to go revert to the default background..
        /// </summary>
        public static string info_background_override {
            get {
                return ResourceManager.GetString("info_background_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will delete all local schema and editor data files then restart the app. Would you like to continue?.
        /// </summary>
        public static string info_clear_cache {
            get {
                return ResourceManager.GetString("info_clear_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following changes require the game to be restarted:.
        /// </summary>
        public static string info_game_restart {
            get {
                return ResourceManager.GetString("info_game_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to continue because Team Fortress 2 is still running. Please close the game then try again..
        /// </summary>
        public static string info_game_running {
            get {
                return ResourceManager.GetString("info_game_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all customizations back to their defaults?.
        /// </summary>
        public static string info_hud_reset {
            get {
                return ResourceManager.GetString("info_hud_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new HUD schema update available. Would you like to restart now to apply the new changes?.
        /// </summary>
        public static string info_hud_update {
            get {
                return ResourceManager.GetString("info_hud_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates are currently available. Please check back later..
        /// </summary>
        public static string info_hud_update_none {
            get {
                return ResourceManager.GetString("info_hud_update_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your tf/custom directory. If an invalid directory is provided, multiple options will be unavailable..
        /// </summary>
        public static string info_path_browser {
            get {
                return ResourceManager.GetString("info_path_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path you have selected does not end with tf/custom. Please try again..
        /// </summary>
        public static string info_path_invalid {
            get {
                return ResourceManager.GetString("info_path_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unsupported HUD was found in the tf/custom folder. Do you want to delete it to continue with the installation?.
        /// </summary>
        public static string info_unsupported_hud_found {
            get {
                return ResourceManager.GetString("info_unsupported_hud_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} customizations applied on {1}..
        /// </summary>
        public static string status_applied {
            get {
                return ResourceManager.GetString("status_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is installed!.
        /// </summary>
        public static string status_installed {
            get {
                return ResourceManager.GetString("status_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not installed!.
        /// </summary>
        public static string status_installed_not {
            get {
                return ResourceManager.GetString("status_installed_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installation finished on {1}..
        /// </summary>
        public static string status_installed_now {
            get {
                return ResourceManager.GetString("status_installed_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tf/custom directory is not set!.
        /// </summary>
        public static string status_path_notset {
            get {
                return ResourceManager.GetString("status_path_notset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} customizations reset on {1}..
        /// </summary>
        public static string status_reset {
            get {
                return ResourceManager.GetString("status_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new HUD..
        /// </summary>
        public static string tooltip_addhud {
            get {
                return ResourceManager.GetString("tooltip_addhud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the documentation..
        /// </summary>
        public static string tooltip_docs {
            get {
                return ResourceManager.GetString("tooltip_docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Team Fortress 2..
        /// </summary>
        public static string tooltip_launch {
            get {
                return ResourceManager.GetString("tooltip_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View options menu..
        /// </summary>
        public static string tooltip_options {
            get {
                return ResourceManager.GetString("tooltip_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the page..
        /// </summary>
        public static string tooltip_refresh {
            get {
                return ResourceManager.GetString("tooltip_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue..
        /// </summary>
        public static string tooltip_report {
            get {
                return ResourceManager.GetString("tooltip_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes.
        /// </summary>
        public static string ui_apply {
            get {
                return ResourceManager.GetString("ui_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by: {0}.
        /// </summary>
        public static string ui_author {
            get {
                return ResourceManager.GetString("ui_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string ui_browse {
            get {
                return ResourceManager.GetString("ui_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-update files (Disable if doing local edits).
        /// </summary>
        public static string ui_check_updates {
            get {
                return ResourceManager.GetString("ui_check_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ui_clear {
            get {
                return ResourceManager.GetString("ui_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache Files.
        /// </summary>
        public static string ui_clear_cache {
            get {
                return ResourceManager.GetString("ui_clear_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string ui_customize {
            get {
                return ResourceManager.GetString("ui_customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tf/custom path.
        /// </summary>
        public static string ui_directory {
            get {
                return ResourceManager.GetString("ui_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string ui_install {
            get {
                return ResourceManager.GetString("ui_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string ui_language {
            get {
                return ResourceManager.GetString("ui_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string ui_language_cn {
            get {
                return ResourceManager.GetString("ui_language_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ui_language_en {
            get {
                return ResourceManager.GetString("ui_language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string ui_language_fr {
            get {
                return ResourceManager.GetString("ui_language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string ui_language_it {
            get {
                return ResourceManager.GetString("ui_language_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian Portuguese.
        /// </summary>
        public static string ui_language_pt {
            get {
                return ResourceManager.GetString("ui_language_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string ui_language_ru {
            get {
                return ResourceManager.GetString("ui_language_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App Settings.
        /// </summary>
        public static string ui_open_app_file {
            get {
                return ResourceManager.GetString("ui_open_app_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Latest Log File.
        /// </summary>
        public static string ui_open_log_file {
            get {
                return ResourceManager.GetString("ui_open_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open User Settings.
        /// </summary>
        public static string ui_open_user_file {
            get {
                return ResourceManager.GetString("ui_open_user_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ui_options {
            get {
                return ResourceManager.GetString("ui_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass tf/custom folder rule.
        /// </summary>
        public static string ui_override_path_rule {
            get {
                return ResourceManager.GetString("ui_override_path_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember crosshair selection.
        /// </summary>
        public static string ui_persist_xhair {
            get {
                return ResourceManager.GetString("ui_persist_xhair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string ui_refresh {
            get {
                return ResourceManager.GetString("ui_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        public static string ui_reinstall {
            get {
                return ResourceManager.GetString("ui_reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Changes.
        /// </summary>
        public static string ui_reset {
            get {
                return ResourceManager.GetString("ui_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string ui_save {
            get {
                return ResourceManager.GetString("ui_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string ui_search {
            get {
                return ResourceManager.GetString("ui_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a HUD.
        /// </summary>
        public static string ui_select {
            get {
                return ResourceManager.GetString("ui_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string ui_splash_cancel {
            get {
                return ResourceManager.GetString("ui_splash_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and caching images....
        /// </summary>
        public static string ui_splash_images {
            get {
                return ResourceManager.GetString("ui_splash_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing application....
        /// </summary>
        public static string ui_splash_initialize {
            get {
                return ResourceManager.GetString("ui_splash_initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading HUD schemas....
        /// </summary>
        public static string ui_splash_schema {
            get {
                return ResourceManager.GetString("ui_splash_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch HUDs.
        /// </summary>
        public static string ui_switch {
            get {
                return ResourceManager.GetString("ui_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF2 HUD Editor.
        /// </summary>
        public static string ui_title {
            get {
                return ResourceManager.GetString("ui_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string ui_uninstall {
            get {
                return ResourceManager.GetString("ui_uninstall", resourceCulture);
            }
        }
    }
}
