//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF2HUD.Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class flawhud : global::System.Configuration.ApplicationSettingsBase {
        
        private static flawhud defaultInstance = ((flawhud)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new flawhud())));
        
        public static flawhud Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#BE1414")]
        public string color_ammo_low {
            get {
                return ((string)(this["color_ammo_low"]));
            }
            set {
                this["color_ammo_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00AA7F")]
        public string color_health_buff {
            get {
                return ((string)(this["color_health_buff"]));
            }
            set {
                this["color_health_buff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#BE1414")]
        public string color_health_low {
            get {
                return ((string)(this["color_health_low"]));
            }
            set {
                this["color_health_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00AA7F")]
        public string color_ubercharge {
            get {
                return ((string)(this["color_ubercharge"]));
            }
            set {
                this["color_ubercharge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F2F2F2")]
        public string color_xhair_normal {
            get {
                return ((string)(this["color_xhair_normal"]));
            }
            set {
                this["color_xhair_normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0000")]
        public string color_xhair_pulse {
            get {
                return ((string)(this["color_xhair_pulse"]));
            }
            set {
                this["color_xhair_pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_code_fonts {
            get {
                return ((bool)(this["toggle_code_fonts"]));
            }
            set {
                this["toggle_code_fonts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_disguise_image {
            get {
                return ((bool)(this["toggle_disguise_image"]));
            }
            set {
                this["toggle_disguise_image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_menu_images {
            get {
                return ((bool)(this["toggle_menu_images"]));
            }
            set {
                this["toggle_menu_images"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_background_stock {
            get {
                return ((bool)(this["toggle_background_stock"]));
            }
            set {
                this["toggle_background_stock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_transparent_viewmodels {
            get {
                return ((bool)(this["toggle_transparent_viewmodels"]));
            }
            set {
                this["toggle_transparent_viewmodels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_xhair_enable {
            get {
                return ((bool)(this["toggle_xhair_enable"]));
            }
            set {
                this["toggle_xhair_enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool toggle_xhair_pulse {
            get {
                return ((bool)(this["toggle_xhair_pulse"]));
            }
            set {
                this["toggle_xhair_pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_xhair_rotate {
            get {
                return ((bool)(this["toggle_xhair_rotate"]));
            }
            set {
                this["toggle_xhair_rotate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int val_xhair_effect {
            get {
                return ((int)(this["val_xhair_effect"]));
            }
            set {
                this["val_xhair_effect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int val_xhair_style {
            get {
                return ((int)(this["val_xhair_style"]));
            }
            set {
                this["val_xhair_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int val_health_style {
            get {
                return ((int)(this["val_health_style"]));
            }
            set {
                this["val_health_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int val_killfeed_rows {
            get {
                return ((int)(this["val_killfeed_rows"]));
            }
            set {
                this["val_killfeed_rows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_lower_stats {
            get {
                return ((bool)(this["toggle_lower_stats"]));
            }
            set {
                this["toggle_lower_stats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FF7F")]
        public string color_target_health {
            get {
                return ((string)(this["color_target_health"]));
            }
            set {
                this["color_target_health"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF00")]
        public string color_target_damage {
            get {
                return ((string)(this["color_target_damage"]));
            }
            set {
                this["color_target_damage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_alt_stats {
            get {
                return ((bool)(this["toggle_alt_stats"]));
            }
            set {
                this["toggle_alt_stats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int val_xhair_size {
            get {
                return ((int)(this["val_xhair_size"]));
            }
            set {
                this["val_xhair_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#B2B2B2")]
        public string color_normal {
            get {
                return ((string)(this["color_normal"]));
            }
            set {
                this["color_normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD700")]
        public string color_unique {
            get {
                return ((string)(this["color_unique"]));
            }
            set {
                this["color_unique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CF6A32")]
        public string color_strange {
            get {
                return ((string)(this["color_strange"]));
            }
            set {
                this["color_strange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#476291")]
        public string color_vintage {
            get {
                return ((string)(this["color_vintage"]));
            }
            set {
                this["color_vintage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#38F3AB")]
        public string color_haunted {
            get {
                return ((string)(this["color_haunted"]));
            }
            set {
                this["color_haunted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4D7455")]
        public string color_genuine {
            get {
                return ((string)(this["color_genuine"]));
            }
            set {
                this["color_genuine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#AA0000")]
        public string color_collectors {
            get {
                return ((string)(this["color_collectors"]));
            }
            set {
                this["color_collectors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#8650AC")]
        public string color_unusual {
            get {
                return ((string)(this["color_unusual"]));
            }
            set {
                this["color_unusual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#70B04A")]
        public string color_community {
            get {
                return ((string)(this["color_community"]));
            }
            set {
                this["color_community"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#A50F79")]
        public string color_valve {
            get {
                return ((string)(this["color_valve"]));
            }
            set {
                this["color_valve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#B0C3D9")]
        public string color_civilian {
            get {
                return ((string)(this["color_civilian"]));
            }
            set {
                this["color_civilian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#5E98D9")]
        public string color_freelance {
            get {
                return ((string)(this["color_freelance"]));
            }
            set {
                this["color_freelance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4B69FF")]
        public string color_mercenary {
            get {
                return ((string)(this["color_mercenary"]));
            }
            set {
                this["color_mercenary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#8847FF")]
        public string color_commando {
            get {
                return ((string)(this["color_commando"]));
            }
            set {
                this["color_commando"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#D32CE6")]
        public string color_assassin {
            get {
                return ((string)(this["color_assassin"]));
            }
            set {
                this["color_assassin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EB4B4B")]
        public string color_elite {
            get {
                return ((string)(this["color_elite"]));
            }
            set {
                this["color_elite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_background_custom {
            get {
                return ((bool)(this["toggle_background_custom"]));
            }
            set {
                this["toggle_background_custom"] = value;
            }
        }
    }
}
