//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF2HUD.Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class flawhud : global::System.Configuration.ApplicationSettingsBase {
        
        private static flawhud defaultInstance = ((flawhud)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new flawhud())));
        
        public static flawhud Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#BE1414")]
        public string color_ammo_low {
            get {
                return ((string)(this["color_ammo_low"]));
            }
            set {
                this["color_ammo_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00AA7F")]
        public string color_health_buff {
            get {
                return ((string)(this["color_health_buff"]));
            }
            set {
                this["color_health_buff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#BE1414")]
        public string color_health_low {
            get {
                return ((string)(this["color_health_low"]));
            }
            set {
                this["color_health_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00AA7F")]
        public string color_uber_bar {
            get {
                return ((string)(this["color_uber_bar"]));
            }
            set {
                this["color_uber_bar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00AA7F")]
        public string color_uber_full {
            get {
                return ((string)(this["color_uber_full"]));
            }
            set {
                this["color_uber_full"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F2F2F2")]
        public string color_xhair_normal {
            get {
                return ((string)(this["color_xhair_normal"]));
            }
            set {
                this["color_xhair_normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0000")]
        public string color_xhair_pulse {
            get {
                return ((string)(this["color_xhair_pulse"]));
            }
            set {
                this["color_xhair_pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hud_updated {
            get {
                return ((bool)(this["hud_updated"]));
            }
            set {
                this["hud_updated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_code_fonts {
            get {
                return ((bool)(this["toggle_code_fonts"]));
            }
            set {
                this["toggle_code_fonts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_disguise_image {
            get {
                return ((bool)(this["toggle_disguise_image"]));
            }
            set {
                this["toggle_disguise_image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_menu_images {
            get {
                return ((bool)(this["toggle_menu_images"]));
            }
            set {
                this["toggle_menu_images"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_stock_backgrounds {
            get {
                return ((bool)(this["toggle_stock_backgrounds"]));
            }
            set {
                this["toggle_stock_backgrounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_transparent_viewmodels {
            get {
                return ((bool)(this["toggle_transparent_viewmodels"]));
            }
            set {
                this["toggle_transparent_viewmodels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_xhair_enable {
            get {
                return ((bool)(this["toggle_xhair_enable"]));
            }
            set {
                this["toggle_xhair_enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_xhair_pulse {
            get {
                return ((bool)(this["toggle_xhair_pulse"]));
            }
            set {
                this["toggle_xhair_pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_xhair_rotate {
            get {
                return ((bool)(this["toggle_xhair_rotate"]));
            }
            set {
                this["toggle_xhair_rotate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int val_xhair_effect {
            get {
                return ((int)(this["val_xhair_effect"]));
            }
            set {
                this["val_xhair_effect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int val_xhair_style {
            get {
                return ((int)(this["val_xhair_style"]));
            }
            set {
                this["val_xhair_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int val_health_style {
            get {
                return ((int)(this["val_health_style"]));
            }
            set {
                this["val_health_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int val_killfeed_rows {
            get {
                return ((int)(this["val_killfeed_rows"]));
            }
            set {
                this["val_killfeed_rows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_lower_stats {
            get {
                return ((bool)(this["toggle_lower_stats"]));
            }
            set {
                this["toggle_lower_stats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FF7F")]
        public string color_target_health {
            get {
                return ((string)(this["color_target_health"]));
            }
            set {
                this["color_target_health"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF00")]
        public string color_target_damage {
            get {
                return ((string)(this["color_target_damage"]));
            }
            set {
                this["color_target_damage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_alt_stats {
            get {
                return ((bool)(this["toggle_alt_stats"]));
            }
            set {
                this["toggle_alt_stats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int val_xhair_size {
            get {
                return ((int)(this["val_xhair_size"]));
            }
            set {
                this["val_xhair_size"] = value;
            }
        }
    }
}
