//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF2HUD.Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class rayshud : global::System.Configuration.ApplicationSettingsBase {
        
        private static rayshud defaultInstance = ((rayshud)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new rayshud())));
        
        public static rayshud Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30FF30")]
        public string color_ammo_clip {
            get {
                return ((string)(this["color_ammo_clip"]));
            }
            set {
                this["color_ammo_clip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF2A82")]
        public string color_ammo_clip_low {
            get {
                return ((string)(this["color_ammo_clip_low"]));
            }
            set {
                this["color_ammo_clip_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#48FFFF")]
        public string color_ammo_reserve {
            get {
                return ((string)(this["color_ammo_reserve"]));
            }
            set {
                this["color_ammo_reserve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF801C")]
        public string color_ammo_reserve_low {
            get {
                return ((string)(this["color_ammo_reserve_low"]));
            }
            set {
                this["color_ammo_reserve_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30FF30")]
        public string color_health_buff {
            get {
                return ((string)(this["color_health_buff"]));
            }
            set {
                this["color_health_buff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30FF30")]
        public string color_health_healed {
            get {
                return ((string)(this["color_health_healed"]));
            }
            set {
                this["color_health_healed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF9900")]
        public string color_health_low {
            get {
                return ((string)(this["color_health_low"]));
            }
            set {
                this["color_health_low"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EBE2CA")]
        public string color_health_normal {
            get {
                return ((string)(this["color_health_normal"]));
            }
            set {
                this["color_health_normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EBE2CA")]
        public string color_uber_bar {
            get {
                return ((string)(this["color_uber_bar"]));
            }
            set {
                this["color_uber_bar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFA500")]
        public string color_uber_flash1 {
            get {
                return ((string)(this["color_uber_flash1"]));
            }
            set {
                this["color_uber_flash1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF4500")]
        public string color_uber_flash2 {
            get {
                return ((string)(this["color_uber_flash2"]));
            }
            set {
                this["color_uber_flash2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3219")]
        public string color_uber_full {
            get {
                return ((string)(this["color_uber_full"]));
            }
            set {
                this["color_uber_full"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F2F2F2")]
        public string color_xhair_normal {
            get {
                return ((string)(this["color_xhair_normal"]));
            }
            set {
                this["color_xhair_normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0000")]
        public string color_xhair_pulse {
            get {
                return ((string)(this["color_xhair_pulse"]));
            }
            set {
                this["color_xhair_pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_alt_player_model {
            get {
                return ((bool)(this["toggle_alt_player_model"]));
            }
            set {
                this["toggle_alt_player_model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_center_select {
            get {
                return ((bool)(this["toggle_center_select"]));
            }
            set {
                this["toggle_center_select"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_chat_bottom {
            get {
                return ((bool)(this["toggle_chat_bottom"]));
            }
            set {
                this["toggle_chat_bottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_classic_menu {
            get {
                return ((bool)(this["toggle_classic_menu"]));
            }
            set {
                this["toggle_classic_menu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_damage_pos {
            get {
                return ((bool)(this["toggle_damage_pos"]));
            }
            set {
                this["toggle_damage_pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_disguise_image {
            get {
                return ((bool)(this["toggle_disguise_image"]));
            }
            set {
                this["toggle_disguise_image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_menu_image {
            get {
                return ((bool)(this["toggle_menu_image"]));
            }
            set {
                this["toggle_menu_image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_metal_pos {
            get {
                return ((bool)(this["toggle_metal_pos"]));
            }
            set {
                this["toggle_metal_pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_min_scoreboard {
            get {
                return ((bool)(this["toggle_min_scoreboard"]));
            }
            set {
                this["toggle_min_scoreboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_transparent_viewmodels {
            get {
                return ((bool)(this["toggle_transparent_viewmodels"]));
            }
            set {
                this["toggle_transparent_viewmodels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggle_xhair_enable {
            get {
                return ((bool)(this["toggle_xhair_enable"]));
            }
            set {
                this["toggle_xhair_enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool toggle_xhair_pulse {
            get {
                return ((bool)(this["toggle_xhair_pulse"]));
            }
            set {
                this["toggle_xhair_pulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int val_health_style {
            get {
                return ((int)(this["val_health_style"]));
            }
            set {
                this["val_health_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int val_main_menu_bg {
            get {
                return ((int)(this["val_main_menu_bg"]));
            }
            set {
                this["val_main_menu_bg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int val_uber_animation {
            get {
                return ((int)(this["val_uber_animation"]));
            }
            set {
                this["val_uber_animation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int val_xhair_effect {
            get {
                return ((int)(this["val_xhair_effect"]));
            }
            set {
                this["val_xhair_effect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int val_xhair_size {
            get {
                return ((int)(this["val_xhair_size"]));
            }
            set {
                this["val_xhair_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int val_xhair_style {
            get {
                return ((int)(this["val_xhair_style"]));
            }
            set {
                this["val_xhair_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int val_killfeed_rows {
            get {
                return ((int)(this["val_killfeed_rows"]));
            }
            set {
                this["val_killfeed_rows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#B2B2B2")]
        public string color_normal {
            get {
                return ((string)(this["color_normal"]));
            }
            set {
                this["color_normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD700")]
        public string color_unique {
            get {
                return ((string)(this["color_unique"]));
            }
            set {
                this["color_unique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CF6A32")]
        public string color_strange {
            get {
                return ((string)(this["color_strange"]));
            }
            set {
                this["color_strange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#476291")]
        public string color_vintage {
            get {
                return ((string)(this["color_vintage"]));
            }
            set {
                this["color_vintage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#38F3AB")]
        public string color_haunted {
            get {
                return ((string)(this["color_haunted"]));
            }
            set {
                this["color_haunted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4D7455")]
        public string color_genuine {
            get {
                return ((string)(this["color_genuine"]));
            }
            set {
                this["color_genuine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#AA0000")]
        public string color_collectors {
            get {
                return ((string)(this["color_collectors"]));
            }
            set {
                this["color_collectors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#8650AC")]
        public string color_unusual {
            get {
                return ((string)(this["color_unusual"]));
            }
            set {
                this["color_unusual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#70B04A")]
        public string color_community {
            get {
                return ((string)(this["color_community"]));
            }
            set {
                this["color_community"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#A50F79")]
        public string color_valve {
            get {
                return ((string)(this["color_valve"]));
            }
            set {
                this["color_valve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#B0C3D9")]
        public string color_civilian {
            get {
                return ((string)(this["color_civilian"]));
            }
            set {
                this["color_civilian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#5E98D9")]
        public string color_freelance {
            get {
                return ((string)(this["color_freelance"]));
            }
            set {
                this["color_freelance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4B69FF")]
        public string color_mercenary {
            get {
                return ((string)(this["color_mercenary"]));
            }
            set {
                this["color_mercenary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#8847FF")]
        public string color_commando {
            get {
                return ((string)(this["color_commando"]));
            }
            set {
                this["color_commando"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#D32CE6")]
        public string color_assassin {
            get {
                return ((string)(this["color_assassin"]));
            }
            set {
                this["color_assassin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EB4B4B")]
        public string color_elite {
            get {
                return ((string)(this["color_elite"]));
            }
            set {
                this["color_elite"] = value;
            }
        }
    }
}
