//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF2HUD.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TF2HUD.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/CriticalFlaw/TF2HUD.Editor/issues.
        /// </summary>
        internal static string app_tracker {
            get {
                return ResourceManager.GetString("app_tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/CriticalFlaw/TF2HUD.Editor/master/Update.xml.
        /// </summary>
        internal static string app_update {
            get {
                return ResourceManager.GetString("app_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/CriticalFlaw/flawhud/archive/master.zip.
        /// </summary>
        internal static string download_flawhud {
            get {
                return ResourceManager.GetString("download_flawhud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/raysfire/rayshud/archive/master.zip.
        /// </summary>
        internal static string download_rayshud {
            get {
                return ResourceManager.GetString("download_rayshud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tf/custom directory must be set to use the editor..
        /// </summary>
        internal static string error_app_directory {
            get {
                return ResourceManager.GetString("error_app_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing {0}..
        /// </summary>
        internal static string error_app_install {
            get {
                return ResourceManager.GetString("error_app_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading {0} settings..
        /// </summary>
        internal static string error_app_load {
            get {
                return ResourceManager.GetString("error_app_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resetting {0} settings..
        /// </summary>
        internal static string error_app_reset {
            get {
                return ResourceManager.GetString("error_app_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving {0} settings..
        /// </summary>
        internal static string error_app_save {
            get {
                return ResourceManager.GetString("error_app_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uninstalling {0}..
        /// </summary>
        internal static string error_app_uninstall {
            get {
                return ResourceManager.GetString("error_app_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the chatbox position..
        /// </summary>
        internal static string error_chat_pos {
            get {
                return ResourceManager.GetString("error_chat_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the color values..
        /// </summary>
        internal static string error_colors {
            get {
                return ResourceManager.GetString("error_colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the damage position..
        /// </summary>
        internal static string error_damage_pos {
            get {
                return ResourceManager.GetString("error_damage_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while toggling the spy disguise image..
        /// </summary>
        internal static string error_disguise_image {
            get {
                return ResourceManager.GetString("error_disguise_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the font selection..
        /// </summary>
        internal static string error_fonts {
            get {
                return ResourceManager.GetString("error_fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the health style..
        /// </summary>
        internal static string error_health_style {
            get {
                return ResourceManager.GetString("error_health_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the killfeed row count..
        /// </summary>
        internal static string error_killfeed {
            get {
                return ResourceManager.GetString("error_killfeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the player stats position..
        /// </summary>
        internal static string error_lower_stats {
            get {
                return ResourceManager.GetString("error_lower_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the main menu style..
        /// </summary>
        internal static string error_main_menu {
            get {
                return ResourceManager.GetString("error_main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the main menu backgrounds..
        /// </summary>
        internal static string error_menu_background {
            get {
                return ResourceManager.GetString("error_menu_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while toggling the main menu class image..
        /// </summary>
        internal static string error_menu_class_image {
            get {
                return ResourceManager.GetString("error_menu_class_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the player model position..
        /// </summary>
        internal static string error_player_model_pos {
            get {
                return ResourceManager.GetString("error_player_model_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the scoreboard style..
        /// </summary>
        internal static string error_scoreboard {
            get {
                return ResourceManager.GetString("error_scoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the team select style..
        /// </summary>
        internal static string error_team_select {
            get {
                return ResourceManager.GetString("error_team_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while toggling transparent viewmodels..
        /// </summary>
        internal static string error_transparent_vm {
            get {
                return ResourceManager.GetString("error_transparent_vm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the ÜberCharge style..
        /// </summary>
        internal static string error_uber_animation {
            get {
                return ResourceManager.GetString("error_uber_animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the crosshair selection..
        /// </summary>
        internal static string error_xhair {
            get {
                return ResourceManager.GetString("error_xhair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while toggling the crosshair pulse..
        /// </summary>
        internal static string error_xhair_pulse {
            get {
                return ResourceManager.GetString("error_xhair_pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\materials\console\background_{2}.
        /// </summary>
        internal static string file_background_upward {
            get {
                return ResourceManager.GetString("file_background_upward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\basechat.res.
        /// </summary>
        internal static string file_basechat {
            get {
                return ResourceManager.GetString("file_basechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\cfg\hud.cfg.
        /// </summary>
        internal static string file_cfg {
            get {
                return ResourceManager.GetString("file_cfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\scripts\chapterbackgrounds.txt.
        /// </summary>
        internal static string file_chapterbackgrounds {
            get {
                return ResourceManager.GetString("file_chapterbackgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\classselection.res.
        /// </summary>
        internal static string file_classselection {
            get {
                return ResourceManager.GetString("file_classselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\clientscheme.res.
        /// </summary>
        internal static string file_clientscheme {
            get {
                return ResourceManager.GetString("file_clientscheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\scheme\clientscheme_colors.res.
        /// </summary>
        internal static string file_clientscheme_colors {
            get {
                return ResourceManager.GetString("file_clientscheme_colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\customizations\main_menu\mainmenuoverride.res.
        /// </summary>
        internal static string file_custom_mainmenu {
            get {
                return ResourceManager.GetString("file_custom_mainmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\customizations\main_menu\mainmenuoverride-classic.res.
        /// </summary>
        internal static string file_custom_mainmenu_classic {
            get {
                return ResourceManager.GetString("file_custom_mainmenu_classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\scripts\hudanimations_custom.txt.
        /// </summary>
        internal static string file_hudanimations {
            get {
                return ResourceManager.GetString("file_hudanimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\huddamageaccount.res.
        /// </summary>
        internal static string file_huddamageaccount {
            get {
                return ResourceManager.GetString("file_huddamageaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\scripts\hudlayout.res.
        /// </summary>
        internal static string file_hudlayout {
            get {
                return ResourceManager.GetString("file_hudlayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\hudplayerclass.res.
        /// </summary>
        internal static string file_hudplayerclass {
            get {
                return ResourceManager.GetString("file_hudplayerclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\hudplayerhealth.res.
        /// </summary>
        internal static string file_hudplayerhealth {
            get {
                return ResourceManager.GetString("file_hudplayerhealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\huditemeffectmeter{2}.res.
        /// </summary>
        internal static string file_itemeffectmeter {
            get {
                return ResourceManager.GetString("file_itemeffectmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\mainmenuoverride.res.
        /// </summary>
        internal static string file_mainmenuoverride {
            get {
                return ResourceManager.GetString("file_mainmenuoverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\hudplayerclass.res.
        /// </summary>
        internal static string file_playerclass {
            get {
                return ResourceManager.GetString("file_playerclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\hudplayerhealth.res.
        /// </summary>
        internal static string file_playerhealth {
            get {
                return ResourceManager.GetString("file_playerhealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\scoreboard.res.
        /// </summary>
        internal static string file_scoreboard {
            get {
                return ResourceManager.GetString("file_scoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui\teammenu.res.
        /// </summary>
        internal static string file_teammenu {
            get {
                return ResourceManager.GetString("file_teammenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing {0} folder has been found. To avoid conflicts, a backup has been created..
        /// </summary>
        internal static string info_create_backup {
            get {
                return ResourceManager.GetString("info_create_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your tf/custom directory. If a valid directory is not provided, the options to use the editor will not be available..
        /// </summary>
        internal static string info_folder_browser {
            get {
                return ResourceManager.GetString("info_folder_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to continue because Team Fortress 2 is still running. Please close it and then try again..
        /// </summary>
        internal static string info_game_running {
            get {
                return ResourceManager.GetString("info_game_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully installed..
        /// </summary>
        internal static string info_install_complete {
            get {
                return ResourceManager.GetString("info_install_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully uninstalled..
        /// </summary>
        internal static string info_uninstall_complete {
            get {
                return ResourceManager.GetString("info_uninstall_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\materials\console\.
        /// </summary>
        internal static string path_console {
            get {
                return ResourceManager.GetString("path_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}\resource\ui.
        /// </summary>
        internal static string path_resource_ui {
            get {
                return ResourceManager.GetString("path_resource_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://huds.tf/site/s-FlawHUD.
        /// </summary>
        internal static string url_flawhud_hudstf {
            get {
                return ResourceManager.GetString("url_flawhud_hudstf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcommunity.com/groups/FlawHUD.
        /// </summary>
        internal static string url_flawhud_steam {
            get {
                return ResourceManager.GetString("url_flawhud_steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://huds.tf/site/s-rayshud--377.
        /// </summary>
        internal static string url_rayshud_hudstf {
            get {
                return ResourceManager.GetString("url_rayshud_hudstf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcommunity.com/groups/rayshud.
        /// </summary>
        internal static string url_rayshud_steam {
            get {
                return ResourceManager.GetString("url_rayshud_steam", resourceCulture);
            }
        }
    }
}
