//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUDEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hud_selected {
            get {
                return ((string)(this["hud_selected"]));
            }
            set {
                this["hud_selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hud_directory {
            get {
                return ((string)(this["hud_directory"]));
            }
            set {
                this["hud_directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string user_language {
            get {
                return ((string)(this["user_language"]));
            }
            set {
                this["user_language"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.criticalflaw.ca/TF2HUD.Editor/")]
        public string app_docs {
            get {
                return ((string)(this["app_docs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/CriticalFlaw/TF2HUD.Editor/master/src/TF2HUD.Ed" +
            "itor/JSON/{0}")]
        public string json_file {
            get {
                return ((string)(this["json_file"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.github.com/repos/CriticalFlaw/TF2HUD.Editor/contents/src/TF2HUD.Edito" +
            "r/JSON")]
        public string json_list {
            get {
                return ((string)(this["json_list"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/CriticalFlaw/TF2HUD.Editor/issues")]
        public string app_tracker {
            get {
                return ((string)(this["app_tracker"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/CriticalFlaw/TF2HUD.Editor/master/Update.xml")]
        public string app_update {
            get {
                return ((string)(this["app_update"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/mastercomfig/mastercomfig/releases/download/9.5.2/mastercomfig" +
            "-transparent-viewmodels-addon.vpk")]
        public string mastercomfig_vpk {
            get {
                return ((string)(this["mastercomfig_vpk"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool app_update_auto {
            get {
                return ((bool)(this["app_update_auto"]));
            }
            set {
                this["app_update_auto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool app_xhair_persist {
            get {
                return ((bool)(this["app_xhair_persist"]));
            }
            set {
                this["app_xhair_persist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool app_xhair_enabled {
            get {
                return ((bool)(this["app_xhair_enabled"]));
            }
            set {
                this["app_xhair_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$")]
        public string app_xhair_style {
            get {
                return ((string)(this["app_xhair_style"]));
            }
            set {
                this["app_xhair_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app_xhair_color {
            get {
                return ((string)(this["app_xhair_color"]));
            }
            set {
                this["app_xhair_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int app_xhair_size {
            get {
                return ((int)(this["app_xhair_size"]));
            }
            set {
                this["app_xhair_size"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Hypnootize/TF2-HUD-Crosshairs/archive/refs/heads/master.zip")]
        public string tf2_hud_crosshairs_zip {
            get {
                return ((string)(this["tf2_hud_crosshairs_zip"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://user-images.githubusercontent.com/6818236/220803776-12f85855-a409-4555-8f" +
            "76-e3877d04bab9.png")]
        public string app_default_bg {
            get {
                return ((string)(this["app_default_bg"]));
            }
            set {
                this["app_default_bg"] = value;
            }
        }
    }
}
