name: .NET Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    
    env:
      Solution_Name: TF2HUD.Editor.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
     
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: msbuild build