name: package (Avalonia)

on:
  workflow_dispatch:
  pull_request:

jobs:
  package:
    runs-on: windows-latest
    
    env:
      Solution_Name: TF2HUD.Editor.slnx

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Restore dependencies
      run: nuget restore src/TF2HUD.Editor.slnx
        
    - name: Publish solution
      run: dotnet publish -c Release --output ./publish
      working-directory: src/HUDEdit
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TF2HUD-Editor
        path: D:\a\TF2HUD.Editor\TF2HUD.Editor\src\HUDEdit\publish\
